print("Listas-------------------------------------------------------------")
print("")
print("Criando um lista de string")
lista = ["A","B", "C"]
print(lista)
print("Adicionando um item")
lista.append("D")
print(lista)
print("Exibindo o intem do indice 2")
print(lista[2])
print("Filtantro um lista pelo inde 'A'")
print(lista.index("A"))
print("Removendo um item da lista")
lista.remove("C")
print(lista)
print("Revertendo a lista")
lista.reverse()
print(lista)
print("Criando uma lista desordenada")
lista2 = [2, 5, 1, 3, 0, 8, 6, 5]
print(lista2)
print("Lista ordenada")
lista2.sort()
print(lista2)
print("")