print("Tipo(Objetos)--------------------------------------------------")
print("")
print("Criacao de um tipo")
tipo=("tiago", "python", "udemy")
print(tipo)
print("Impressão por indice")
print(tipo[1])
print("Impressão por indices")
print(tipo[1:52])
print("")